use anyhow::{Context, Result};
use minijinja::context;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::config::DevBoxConfig;
use crate::output;

/// Write content to a file only if it differs from the current content.
/// Returns true if the file was written, false if it was already up to date.
fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.exists() {
        let existing = fs::read_to_string(path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        if existing == content {
            return Ok(false);
        }
    }
    fs::write(path, content).with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(true)
}

const HEADER_TEMPLATE: &str = "# Generated by dev-box v{version} — do not edit manually.\n# To modify, edit dev-box.toml and run: dev-box generate\n";

/// Create a minijinja environment with embedded templates.
fn create_template_env() -> minijinja::Environment<'static> {
    let mut env = minijinja::Environment::new();
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.add_template("Dockerfile", include_str!("templates/Dockerfile.j2"))
        .expect("Failed to add Dockerfile template");
    env.add_template(
        "docker-compose.yml",
        include_str!("templates/docker-compose.yml.j2"),
    )
    .expect("Failed to add docker-compose template");
    env
}

/// Generate all devcontainer files from the config.
pub fn generate_all(config: &DevBoxConfig) -> Result<()> {
    let devcontainer_dir = Path::new(crate::config::DEVCONTAINER_DIR);
    fs::create_dir_all(devcontainer_dir).context("Failed to create .devcontainer directory")?;

    output::info("Generating devcontainer files...");

    if generate_dockerfile(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/Dockerfile");
    }

    if generate_docker_compose(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/docker-compose.yml");
    }

    if generate_devcontainer_json(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/devcontainer.json");
    }

    Ok(())
}

/// Generate the Dockerfile. Returns true if file was written.
fn generate_dockerfile(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.dev_box.version);

    // Read Dockerfile.local if it exists
    let local_content = {
        let local_dockerfile = dir.join("Dockerfile.local");
        if local_dockerfile.exists() {
            let raw = fs::read_to_string(&local_dockerfile)
                .with_context(|| format!("Failed to read {}", local_dockerfile.display()))?;
            if raw.trim().is_empty() {
                None
            } else {
                // Ensure trailing newline for clean template output
                let mut content = raw;
                if !content.ends_with('\n') {
                    content.push('\n');
                }
                // Remove the trailing newline since the template adds one
                Some(content.trim_end_matches('\n').to_string())
            }
        } else {
            None
        }
    };

    let env = create_template_env();
    let tmpl = env
        .get_template("Dockerfile")
        .context("Failed to load Dockerfile template")?;

    let content = tmpl
        .render(context! {
            header => header,
            registry => crate::config::IMAGE_REGISTRY,
            image => config.dev_box.image.to_string(),
            version => config.dev_box.version,
            extra_packages => config.container.extra_packages,
            local_content => local_content,
        })
        .context("Failed to render Dockerfile template")?;

    write_if_changed(&dir.join("Dockerfile"), &content)
}

/// Generate docker-compose.yml. Returns true if file was written.
fn generate_docker_compose(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.dev_box.version);
    let workspace_dir = config.workspace_dir();

    // Compose file lives in .devcontainer/, so paths must be relative to that dir.
    // host_root_dir() returns ".root" (relative to project root), so we prepend "../".
    let host_root = config.host_root_dir();
    let host_root_str = if host_root.is_relative() {
        format!("../{}", host_root.to_string_lossy())
    } else {
        host_root.to_string_lossy().into_owned()
    };

    // Build environment map (BTreeMap for sorted keys)
    let mut env_vars: BTreeMap<String, String> = BTreeMap::new();
    env_vars.insert("TZ".to_string(), "Europe/Berlin".to_string());
    env_vars.insert("LANG".to_string(), "en_US.UTF-8".to_string());
    env_vars.insert("COLORTERM".to_string(), "truecolor".to_string());
    env_vars.insert("TERM".to_string(), "xterm-256color".to_string());
    if config.audio.enabled {
        env_vars.insert(
            "PULSE_SERVER".to_string(),
            config.audio.pulse_server.clone(),
        );
        env_vars.insert("AUDIODRIVER".to_string(), "pulseaudio".to_string());
    }

    for (k, v) in &config.container.environment {
        env_vars.insert(k.clone(), v.clone());
    }

    // Build list of AI provider strings for template
    let ai_providers: Vec<String> = config.ai.providers.iter().map(|p| p.to_string()).collect();

    // Container home path
    let container_home = config.container_home();

    // GIT_CONFIG_GLOBAL must use the container home path
    env_vars.insert(
        "GIT_CONFIG_GLOBAL".to_string(),
        format!("{}/.config/git/config", container_home),
    );

    // Escape values for YAML double-quoted strings
    let escaped_env: BTreeMap<String, String> = env_vars
        .iter()
        .map(|(k, v)| {
            let escaped = v.replace('\\', "\\\\").replace('"', "\\\"");
            (k.clone(), escaped)
        })
        .collect();

    let env_keys: Vec<String> = escaped_env.keys().cloned().collect();

    let env = create_template_env();
    let tmpl = env
        .get_template("docker-compose.yml")
        .context("Failed to load docker-compose template")?;

    let content = tmpl
        .render(context! {
            header => header,
            name => config.container.name,
            hostname => config.container.hostname,
            workspace_dir => workspace_dir,
            host_root => host_root_str,
            container_home => container_home,
            audio_enabled => config.audio.enabled,
            ai_providers => ai_providers,
            extra_volumes => config.container.extra_volumes,
            env_keys => env_keys,
            env_vals => escaped_env,
            ports => config.container.ports,
        })
        .context("Failed to render docker-compose template")?;

    write_if_changed(&dir.join("docker-compose.yml"), &content)
}

/// Generate devcontainer.json. Returns true if file was written.
fn generate_devcontainer_json(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let name = &config.container.name;
    let image = &config.dev_box.image;

    // Build extensions list
    let mut extensions: Vec<String> = vec![];
    if image.contains_python() {
        extensions.push("ms-python.python".to_string());
    }
    if image.contains_rust() {
        extensions.push("rust-lang.rust-analyzer".to_string());
    }
    if image.contains_latex() {
        extensions.push("james-yu.latex-workshop".to_string());
        extensions.push("mblode.zotero".to_string());
    }
    if image.contains_typst() {
        extensions.push("myriad-dreamin.tinymist".to_string());
    }

    // Append user-specified VS Code extensions
    for ext in &config.container.vscode_extensions {
        extensions.push(ext.clone());
    }

    // Build VS Code settings — start with base, add flavor-specific
    let mut settings = serde_json::json!({
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.fontFamily": "'FiraCode Nerd Font', 'Hack Nerd Font', 'JetBrainsMono Nerd Font', monospace",
        "terminal.integrated.profiles.linux": {
            "bash": {
                "path": "/bin/bash"
            },
            "claude": {
                "path": "/usr/local/bin/claude"
            },
            "zellij": {
                "path": "/usr/local/bin/zellij",
                "args": ["--layout", "dev"]
            }
        }
    });

    // LaTeX Workshop settings — matches proven setup from derived projects
    if image.contains_latex() {
        let latex_settings = serde_json::json!({
            "latex-workshop.latex.outDir": "./out",
            "latex-workshop.view.pdf.viewer": "tab",
            "latex-workshop.latex.tools": [
                {
                    "name": "latexmk-lualatex",
                    "command": "latexmk",
                    "args": [
                        "--shell-escape",
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdflatex=lualatex",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "latexmk-pdflatex",
                    "command": "latexmk",
                    "args": [
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "biber",
                    "command": "biber",
                    "args": [
                        "--input-directory=out",
                        "--output-directory=out",
                        "%DOCFILE%"
                    ]
                }
            ],
            "latex-workshop.latex.recipes": [
                {
                    "name": "latexmk (lualatex)",
                    "tools": ["latexmk-lualatex"]
                },
                {
                    "name": "latexmk (pdflatex)",
                    "tools": ["latexmk-pdflatex"]
                },
                {
                    "name": "latexmk (lualatex) + biber",
                    "tools": ["latexmk-lualatex", "biber", "latexmk-lualatex"]
                }
            ],
            "latex-workshop.latex.autoBuild.run": "onSave",
            "latex-workshop.latex.clean.fileTypes": [
                "*.aux", "*.bbl", "*.blg", "*.fdb_latexmk", "*.fls",
                "*.log", "*.out", "*.synctex.gz", "*.toc", "*.lof",
                "*.lot", "*.nav", "*.snm", "*.vrb", "*.bcf", "*.run.xml"
            ]
        });
        for (k, v) in latex_settings.as_object().unwrap() {
            settings
                .as_object_mut()
                .unwrap()
                .insert(k.clone(), v.clone());
        }
    }

    // Use serde_json for proper JSON formatting
    let mut devcontainer = serde_json::json!({
        "name": name,
        "dockerComposeFile": "docker-compose.yml",
        "service": name,
        "workspaceFolder": "/workspace",
        "overrideCommand": true,
        "remoteUser": config.container.user,
        "customizations": {
            "vscode": {
                "extensions": extensions,
                "settings": settings
            }
        }
    });

    // Insert postCreateCommand if configured
    if let Some(cmd) = &config.container.post_create_command {
        devcontainer
            .as_object_mut()
            .unwrap()
            .insert("postCreateCommand".to_string(), serde_json::json!(cmd));
    }

    // Prevent VS Code from auto-forwarding the PulseAudio port (fixes #11)
    if config.audio.enabled {
        // Extract port from pulse_server string (e.g., "tcp:host.docker.internal:4714")
        let port = config
            .audio
            .pulse_server
            .rsplit(':')
            .next()
            .unwrap_or("4714");
        devcontainer.as_object_mut().unwrap().insert(
            "portsAttributes".to_string(),
            serde_json::json!({
                port: { "onAutoForward": "ignore" }
            }),
        );
    }

    // Serialize with pretty formatting
    let json_str = serde_json::to_string_pretty(&devcontainer)
        .context("Failed to serialize devcontainer.json")?;

    // Add the header as a comment at the top (JSON doesn't support comments,
    // but devcontainer.json does via jsonc)
    let header = format!(
        "// Generated by dev-box v{} — do not edit manually.\n// To modify, edit dev-box.toml and run: dev-box generate\n",
        config.dev_box.version
    );

    write_if_changed(
        &dir.join("devcontainer.json"),
        &format!("{}{}\n", header, json_str),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;
    use std::collections::HashMap;

    fn make_config(image: ImageFlavor, audio_enabled: bool) -> DevBoxConfig {
        DevBoxConfig {
            dev_box: DevBoxSection {
                version: "1.2.3".to_string(),
                image,
                process: ProcessFlavor::Minimal,
            },
            container: ContainerSection {
                name: "test-ctr".to_string(),
                hostname: "test-host".to_string(),
                user: "root".to_string(),
                ports: vec![],
                extra_packages: vec![],
                extra_volumes: vec![],
                environment: HashMap::new(),
                post_create_command: None,
                vscode_extensions: vec![],
            },
            context: ContextSection::default(),
            ai: crate::config::AiSection::default(),
            audio: AudioSection {
                enabled: audio_enabled,
                pulse_server: "tcp:localhost:4714".to_string(),
            },
        }
    }

    #[test]
    fn generate_all_creates_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let devcontainer = dir.path().join(".devcontainer");
        // We need to run generate functions directly on the temp dir
        // Since generate_all uses relative paths, we test the individual generators
        fs::create_dir_all(&devcontainer).unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, &devcontainer).unwrap();
        generate_docker_compose(&config, &devcontainer).unwrap();
        generate_devcontainer_json(&config, &devcontainer).unwrap();

        assert!(devcontainer.join("Dockerfile").exists());
        assert!(devcontainer.join("docker-compose.yml").exists());
        assert!(devcontainer.join("devcontainer.json").exists());
    }

    #[test]
    fn dockerfile_contains_correct_from_image() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Python, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains(&format!(
                "FROM {}:python-v{} AS dev-box",
                crate::config::IMAGE_REGISTRY,
                config.dev_box.version
            )),
            "Dockerfile should reference python image with correct tag format and stage alias"
        );
    }

    #[test]
    fn dockerfile_includes_extra_packages() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.extra_packages = vec!["ripgrep".to_string(), "fd-find".to_string()];
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("ripgrep"), "should include ripgrep");
        assert!(content.contains("fd-find"), "should include fd-find");
        assert!(
            content.contains("apt-get install"),
            "should have apt-get install"
        );
    }

    #[test]
    fn dockerfile_no_extra_run_when_no_packages() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("apt-get"),
            "should not have apt-get when no extra packages"
        );
    }

    #[test]
    fn compose_contains_container_name_and_hostname() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("container_name: test-ctr"));
        assert!(content.contains("hostname: test-host"));
    }

    #[test]
    fn compose_includes_audio_when_enabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, true);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("PULSE_SERVER"),
            "should have PULSE_SERVER env"
        );
        assert!(
            content.contains("AUDIODRIVER"),
            "should have AUDIODRIVER env"
        );
        assert!(content.contains(".asoundrc"), "should mount .asoundrc");
    }

    #[test]
    fn compose_excludes_audio_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("PULSE_SERVER"));
        assert!(!content.contains("AUDIODRIVER"));
        assert!(!content.contains(".asoundrc"));
    }

    #[test]
    fn compose_includes_extra_volumes() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.extra_volumes = vec![ExtraVolume {
            source: "/host/data".to_string(),
            target: "/container/data".to_string(),
            read_only: true,
        }];
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("/host/data:/container/data:ro"));
    }

    #[test]
    fn compose_includes_extra_environment() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config
            .container
            .environment
            .insert("FOO".to_string(), "bar".to_string());
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("FOO: \"bar\""));
    }

    #[test]
    fn dockerfile_appends_local_when_present() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "RUN npx playwright install --with-deps chromium\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("# Project-specific layers (from Dockerfile.local)"),
            "should have local layers comment"
        );
        assert!(
            content.contains("playwright"),
            "should include Dockerfile.local content"
        );
    }

    #[test]
    fn dockerfile_skips_empty_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        fs::write(dir.path().join("Dockerfile.local"), "  \n").unwrap();
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment for empty file"
        );
    }

    #[test]
    fn dockerfile_works_without_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment when no Dockerfile.local"
        );
    }

    #[test]
    fn dockerfile_local_with_multistage() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Python, false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "FROM node:20 AS node-builder\nRUN npm ci\n\nFROM dev-box\nCOPY --from=node-builder /app /app\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("FROM node:20 AS node-builder"));
        assert!(content.contains("FROM dev-box"));
        assert!(content.contains("COPY --from=node-builder"));
    }

    #[test]
    fn devcontainer_json_python_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Python, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
    }

    #[test]
    fn devcontainer_json_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Latex, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("james-yu.latex-workshop"));
        assert!(content.contains("mblode.zotero"));
    }

    #[test]
    fn devcontainer_json_rust_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Rust, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("rust-lang.rust-analyzer"));
    }

    #[test]
    fn devcontainer_json_python_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::PythonLatex, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn devcontainer_json_typst_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Typst, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_python_typst_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::PythonTypst, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_includes_post_create_command() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.post_create_command = Some("pip install foo".to_string());
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("postCreateCommand"),
            "should contain postCreateCommand key"
        );
        assert!(
            content.contains("pip install foo"),
            "should contain the command value"
        );
    }

    #[test]
    fn devcontainer_json_includes_custom_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.vscode_extensions = vec!["eamodio.gitlens".to_string()];
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("eamodio.gitlens"),
            "should contain custom extension"
        );
    }

    #[test]
    fn devcontainer_json_base_no_extra_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("ms-python.python"));
        assert!(!content.contains("rust-lang.rust-analyzer"));
        assert!(!content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn dockerfile_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.starts_with("# Generated by dev-box v1.2.3"));
    }

    #[test]
    fn compose_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.starts_with("# Generated by dev-box v1.2.3"));
    }

    #[test]
    fn devcontainer_json_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.starts_with("// Generated by dev-box v1.2.3"));
    }
}
