use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::config::DevBoxConfig;
use crate::output;

/// Write content to a file only if it differs from the current content.
/// Returns true if the file was written, false if it was already up to date.
fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.exists() {
        let existing = fs::read_to_string(path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        if existing == content {
            return Ok(false);
        }
    }
    fs::write(path, content)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(true)
}

const HEADER_TEMPLATE: &str = "# Generated by dev-box v{version} — do not edit manually.\n# To modify, edit dev-box.toml and run: dev-box generate\n";

/// Generate all devcontainer files from the config.
pub fn generate_all(config: &DevBoxConfig) -> Result<()> {
    let devcontainer_dir = Path::new(crate::config::DEVCONTAINER_DIR);
    fs::create_dir_all(devcontainer_dir)
        .context("Failed to create .devcontainer directory")?;

    output::info("Generating devcontainer files...");

    if generate_dockerfile(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/Dockerfile");
    }

    if generate_docker_compose(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/docker-compose.yml");
    }

    if generate_devcontainer_json(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/devcontainer.json");
    }

    Ok(())
}

/// Generate the Dockerfile. Returns true if file was written.
fn generate_dockerfile(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.dev_box.version);
    let image = &config.dev_box.image;

    let mut content = format!(
        "{header}\
FROM {registry}/{image}:latest\n",
        header = header,
        registry = crate::config::IMAGE_REGISTRY,
        image = image,
    );

    if !config.container.extra_packages.is_empty() {
        content.push_str("\n# Extra packages from dev-box.toml\n");
        content.push_str("RUN apt-get update && apt-get install -y --no-install-recommends \\\n");
        for (i, pkg) in config.container.extra_packages.iter().enumerate() {
            if i < config.container.extra_packages.len() - 1 {
                content.push_str(&format!("    {} \\\n", pkg));
            } else {
                content.push_str(&format!("    {}\n", pkg));
            }
        }
        content.push_str("    && rm -rf /var/lib/apt/lists/*\n");
    }

    write_if_changed(&dir.join("Dockerfile"), &content)
}

/// Generate docker-compose.yml. Returns true if file was written.
fn generate_docker_compose(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.dev_box.version);
    let name = &config.container.name;
    let hostname = &config.container.hostname;
    let workspace_dir = config.workspace_dir();
    let host_root = config.host_root_dir();
    let host_root_str = host_root.to_string_lossy();

    // Build volumes list
    let mut volumes = vec![
        format!("      - ${{WORKSPACE_DIR:-{workspace_dir}}}:/workspace"),
        format!("      - {host_root_str}/.ssh:/root/.ssh:ro"),
        format!("      - {host_root_str}/.vim:/root/.vim"),
        format!("      - {host_root_str}/.config/zellij:/root/.config/zellij"),
        format!("      - {host_root_str}/.config/git:/root/.config/git"),
        format!("      - {host_root_str}/.claude:/root/.claude"),
    ];

    if config.audio.enabled {
        volumes.push(format!("      - {host_root_str}/.asoundrc:/root/.asoundrc:ro"));
    }

    for vol in &config.container.extra_volumes {
        let ro = if vol.read_only { ":ro" } else { "" };
        volumes.push(format!("      - {}:{}{}", vol.source, vol.target, ro));
    }

    // Build environment map
    let mut env: BTreeMap<String, String> = BTreeMap::new();
    env.insert("TZ".to_string(), "Europe/Berlin".to_string());
    env.insert("LANG".to_string(), "en_US.UTF-8".to_string());
    env.insert("COLORTERM".to_string(), "truecolor".to_string());
    env.insert("TERM".to_string(), "xterm-256color".to_string());
    env.insert(
        "GIT_CONFIG_GLOBAL".to_string(),
        "/root/.config/git/config".to_string(),
    );

    if config.audio.enabled {
        env.insert("PULSE_SERVER".to_string(), config.audio.pulse_server.clone());
        env.insert("AUDIODRIVER".to_string(), "pulseaudio".to_string());
    }

    for (k, v) in &config.container.environment {
        env.insert(k.clone(), v.clone());
    }

    let env_lines: Vec<String> = env
        .iter()
        .map(|(k, v)| format!("      {}: \"{}\"", k, v))
        .collect();

    // Build ports
    let ports_section = if config.container.ports.is_empty() {
        String::new()
    } else {
        let port_lines: Vec<String> = config
            .container
            .ports
            .iter()
            .map(|p| format!("      - \"{}\"", p))
            .collect();
        format!("    ports:\n{}\n", port_lines.join("\n"))
    };

    let content = format!(
        "{header}\
services:
  {name}:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {name}
    hostname: {hostname}
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
{volumes}
    environment:
{env_lines}
{ports_section}    command: sleep infinity
",
        header = header,
        name = name,
        hostname = hostname,
        volumes = volumes.join("\n"),
        env_lines = env_lines.join("\n"),
        ports_section = ports_section,
    );

    write_if_changed(&dir.join("docker-compose.yml"), &content)
}

/// Generate devcontainer.json. Returns true if file was written.
fn generate_devcontainer_json(config: &DevBoxConfig, dir: &Path) -> Result<bool> {
    let name = &config.container.name;
    let image = &config.dev_box.image;

    // Build extensions list
    let mut extensions: Vec<String> = vec![];
    if image.contains_python() {
        extensions.push("ms-python.python".to_string());
    }
    if image.contains_rust() {
        extensions.push("rust-lang.rust-analyzer".to_string());
    }
    if image.contains_latex() {
        extensions.push("james-yu.latex-workshop".to_string());
        extensions.push("mblode.zotero".to_string());
    }

    // Use serde_json for proper JSON formatting
    let devcontainer = serde_json::json!({
        "name": name,
        "dockerComposeFile": "docker-compose.yml",
        "service": name,
        "workspaceFolder": "/workspace",
        "overrideCommand": true,
        "remoteUser": "root",
        "customizations": {
            "vscode": {
                "extensions": extensions,
                "settings": {
                    "terminal.integrated.defaultProfile.linux": "zellij",
                    "terminal.integrated.profiles.linux": {
                        "bash": {
                            "path": "/bin/bash"
                        },
                        "claude": {
                            "path": "/usr/local/bin/claude"
                        },
                        "zellij": {
                            "path": "/usr/local/bin/zellij",
                            "args": ["--layout", "dev"]
                        }
                    }
                }
            }
        }
    });

    // Serialize with pretty formatting
    let json_str = serde_json::to_string_pretty(&devcontainer)
        .context("Failed to serialize devcontainer.json")?;

    // Add the header as a comment at the top (JSON doesn't support comments,
    // but devcontainer.json does via jsonc)
    let header = format!(
        "// Generated by dev-box v{} — do not edit manually.\n// To modify, edit dev-box.toml and run: dev-box generate\n",
        config.dev_box.version
    );

    write_if_changed(&dir.join("devcontainer.json"), &format!("{}{}\n", header, json_str))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;
    use std::collections::HashMap;

    fn make_config(image: ImageFlavor, audio_enabled: bool) -> DevBoxConfig {
        DevBoxConfig {
            dev_box: DevBoxSection {
                version: "1.2.3".to_string(),
                image,
                process: ProcessFlavor::Minimal,
            },
            container: ContainerSection {
                name: "test-ctr".to_string(),
                hostname: "test-host".to_string(),
                ports: vec![],
                extra_packages: vec![],
                extra_volumes: vec![],
                environment: HashMap::new(),
            },
            context: ContextSection::default(),
            audio: AudioSection {
                enabled: audio_enabled,
                pulse_server: "tcp:localhost:4714".to_string(),
            },
        }
    }

    #[test]
    fn generate_all_creates_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let devcontainer = dir.path().join(".devcontainer");
        // We need to run generate functions directly on the temp dir
        // Since generate_all uses relative paths, we test the individual generators
        fs::create_dir_all(&devcontainer).unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, &devcontainer).unwrap();
        generate_docker_compose(&config, &devcontainer).unwrap();
        generate_devcontainer_json(&config, &devcontainer).unwrap();

        assert!(devcontainer.join("Dockerfile").exists());
        assert!(devcontainer.join("docker-compose.yml").exists());
        assert!(devcontainer.join("devcontainer.json").exists());
    }

    #[test]
    fn dockerfile_contains_correct_from_image() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Python, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains(&format!("FROM {}/python:latest", crate::config::IMAGE_REGISTRY)), "Dockerfile should reference python image");
    }

    #[test]
    fn dockerfile_includes_extra_packages() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.extra_packages = vec!["ripgrep".to_string(), "fd-find".to_string()];
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("ripgrep"), "should include ripgrep");
        assert!(content.contains("fd-find"), "should include fd-find");
        assert!(content.contains("apt-get install"), "should have apt-get install");
    }

    #[test]
    fn dockerfile_no_extra_run_when_no_packages() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(!content.contains("apt-get"), "should not have apt-get when no extra packages");
    }

    #[test]
    fn compose_contains_container_name_and_hostname() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("container_name: test-ctr"));
        assert!(content.contains("hostname: test-host"));
    }

    #[test]
    fn compose_includes_audio_when_enabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, true);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("PULSE_SERVER"), "should have PULSE_SERVER env");
        assert!(content.contains("AUDIODRIVER"), "should have AUDIODRIVER env");
        assert!(content.contains(".asoundrc"), "should mount .asoundrc");
    }

    #[test]
    fn compose_excludes_audio_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("PULSE_SERVER"));
        assert!(!content.contains("AUDIODRIVER"));
        assert!(!content.contains(".asoundrc"));
    }

    #[test]
    fn compose_includes_extra_volumes() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.extra_volumes = vec![ExtraVolume {
            source: "/host/data".to_string(),
            target: "/container/data".to_string(),
            read_only: true,
        }];
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("/host/data:/container/data:ro"));
    }

    #[test]
    fn compose_includes_extra_environment() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(ImageFlavor::Base, false);
        config.container.environment.insert("FOO".to_string(), "bar".to_string());
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("FOO: \"bar\""));
    }

    #[test]
    fn devcontainer_json_python_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Python, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
    }

    #[test]
    fn devcontainer_json_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Latex, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("james-yu.latex-workshop"));
        assert!(content.contains("mblode.zotero"));
    }

    #[test]
    fn devcontainer_json_rust_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Rust, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("rust-lang.rust-analyzer"));
    }

    #[test]
    fn devcontainer_json_python_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::PythonLatex, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn devcontainer_json_base_no_extra_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("ms-python.python"));
        assert!(!content.contains("rust-lang.rust-analyzer"));
        assert!(!content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn dockerfile_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_dockerfile(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.starts_with("# Generated by dev-box v1.2.3"));
    }

    #[test]
    fn compose_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_docker_compose(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.starts_with("# Generated by dev-box v1.2.3"));
    }

    #[test]
    fn devcontainer_json_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(ImageFlavor::Base, false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.starts_with("// Generated by dev-box v1.2.3"));
    }
}
