use anyhow::{Context, Result};
use minijinja::context;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::config::AiboxConfig;
use crate::output;

fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    crate::context::write_if_changed(path, content)
}

const HEADER_TEMPLATE: &str = "# Generated by aibox v{version} — do not edit manually.\n# To modify, edit aibox.toml and run: aibox sync\n";

/// Create a minijinja environment with embedded templates.
fn create_template_env() -> minijinja::Environment<'static> {
    let mut env = minijinja::Environment::new();
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.add_template("Dockerfile", include_str!("templates/Dockerfile.j2"))
        .expect("Failed to add Dockerfile template");
    env.add_template(
        "docker-compose.yml",
        include_str!("templates/docker-compose.yml.j2"),
    )
    .expect("Failed to add docker-compose template");
    env
}

/// Generate all devcontainer files from the config.
pub fn generate_all(config: &AiboxConfig) -> Result<()> {
    let devcontainer_dir = Path::new(crate::config::DEVCONTAINER_DIR);
    fs::create_dir_all(devcontainer_dir).context("Failed to create .devcontainer directory")?;

    output::info("Generating devcontainer files...");

    // Create template environment once and reuse for all template-based files
    let env = create_template_env();

    if generate_dockerfile(config, devcontainer_dir, &env)? {
        output::ok("Generated .devcontainer/Dockerfile");
    }

    if generate_docker_compose(config, devcontainer_dir, &env)? {
        output::ok("Generated .devcontainer/docker-compose.yml");
    }

    if generate_devcontainer_json(config, devcontainer_dir)? {
        output::ok("Generated .devcontainer/devcontainer.json");
    }

    Ok(())
}

/// Generate the Dockerfile. Returns true if file was written.
fn generate_dockerfile(
    config: &AiboxConfig,
    dir: &Path,
    env: &minijinja::Environment<'static>,
) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.aibox.version);

    // Read Dockerfile.local if it exists
    let local_content = {
        let local_dockerfile = dir.join("Dockerfile.local");
        match fs::read_to_string(&local_dockerfile) {
            Ok(raw) => {
                let trimmed = raw.trim_end_matches('\n');
                if trimmed.trim().is_empty() {
                    None
                } else {
                    Some(trimmed.to_string())
                }
            }
            Err(_) => None,
        }
    };

    let tmpl = env
        .get_template("Dockerfile")
        .context("Failed to load Dockerfile template")?;

    // Build addon Dockerfile content (builder stages + runtime commands).
    // AI providers are resolved into addons at config load time, so they
    // flow through this pipeline automatically — no hardcoded template logic.
    let addon_output = crate::addons::generate_dockerfile_content(&config.addons)?;
    let addon_builder_stages = addon_output.builder_stages;
    let addon_commands = addon_output.runtime_commands;

    let content = tmpl
        .render(context! {
            header => header,
            registry => crate::config::IMAGE_REGISTRY,
            image => format!("base-{}", config.aibox.base),
            version => config.aibox.version,
            extra_packages => config.container.extra_packages,
            addon_builder_stages => addon_builder_stages,
            addon_commands => addon_commands,
            local_content => local_content,
        })
        .context("Failed to render Dockerfile template")?;

    write_if_changed(&dir.join("Dockerfile"), &content)
}

/// Generate docker-compose.yml. Returns true if file was written.
fn generate_docker_compose(
    config: &AiboxConfig,
    dir: &Path,
    env: &minijinja::Environment<'static>,
) -> Result<bool> {
    let header = HEADER_TEMPLATE.replace("{version}", &config.aibox.version);
    let workspace_dir = config.workspace_dir();

    // Compose file lives in .devcontainer/, so paths must be relative to that dir.
    // host_root_dir() returns ".root" (relative to project root), so we prepend "../".
    let host_root = config.host_root_dir();
    let host_root_str = if host_root.is_relative() {
        format!("../{}", host_root.to_string_lossy())
    } else {
        host_root.to_string_lossy().into_owned()
    };

    // Build environment map (BTreeMap for sorted keys)
    let mut env_vars: BTreeMap<String, String> = BTreeMap::new();
    env_vars.insert("TZ".to_string(), "Europe/Berlin".to_string());
    env_vars.insert("LANG".to_string(), "en_US.UTF-8".to_string());
    env_vars.insert("COLORTERM".to_string(), "truecolor".to_string());
    env_vars.insert("TERM".to_string(), "xterm-256color".to_string());
    if config.audio.enabled {
        env_vars.insert(
            "PULSE_SERVER".to_string(),
            config.audio.pulse_server.clone(),
        );
        env_vars.insert("AUDIODRIVER".to_string(), "pulseaudio".to_string());
    }

    for (k, v) in &config.container.environment {
        env_vars.insert(k.clone(), v.clone());
    }

    // Build list of AI provider strings for template
    let ai_providers: Vec<String> = config.ai.providers.iter().map(|p| p.to_string()).collect();

    // Container home path
    let container_home = config.container_home();

    // GIT_CONFIG_GLOBAL must use the container home path
    env_vars.insert(
        "GIT_CONFIG_GLOBAL".to_string(),
        format!("{}/.config/git/config", container_home),
    );

    // Escape values for YAML double-quoted strings
    let escaped_env: BTreeMap<String, String> = env_vars
        .iter()
        .map(|(k, v)| {
            let escaped = v.replace('\\', "\\\\").replace('"', "\\\"");
            (k.clone(), escaped)
        })
        .collect();

    let env_keys: Vec<String> = escaped_env.keys().cloned().collect();

    let tmpl = env
        .get_template("docker-compose.yml")
        .context("Failed to load docker-compose template")?;

    let content = tmpl
        .render(context! {
            header => header,
            name => config.container.name,
            hostname => config.container.hostname,
            workspace_dir => workspace_dir,
            host_root => host_root_str,
            container_home => container_home,
            audio_enabled => config.audio.enabled,
            ai_providers => ai_providers,
            extra_volumes => config.container.extra_volumes,
            env_keys => env_keys,
            env_vals => escaped_env,
            ports => config.container.ports,
        })
        .context("Failed to render docker-compose template")?;

    write_if_changed(&dir.join("docker-compose.yml"), &content)
}

/// Generate devcontainer.json. Returns true if file was written.
fn generate_devcontainer_json(config: &AiboxConfig, dir: &Path) -> Result<bool> {
    let name = &config.container.name;
    let addons = &config.addons;

    // Build extensions list
    let mut extensions: Vec<String> = vec![];
    if addons.has_python() {
        extensions.push("ms-python.python".to_string());
    }
    if addons.has_rust() {
        extensions.push("rust-lang.rust-analyzer".to_string());
    }
    if addons.has_latex() {
        extensions.push("james-yu.latex-workshop".to_string());
        extensions.push("mblode.zotero".to_string());
    }
    if addons.has_addon("typst") {
        extensions.push("myriad-dreamin.tinymist".to_string());
    }
    if addons.has_node() {
        extensions.push("dbaeumer.vscode-eslint".to_string());
    }
    if addons.has_addon("go") {
        extensions.push("golang.go".to_string());
    }

    // Append user-specified VS Code extensions
    for ext in &config.container.vscode_extensions {
        extensions.push(ext.clone());
    }

    // Build VS Code terminal profiles — include configured AI providers
    let mut terminal_profiles = serde_json::json!({
        "bash": {
            "path": "/bin/bash"
        },
        "zellij": {
            "path": "/usr/local/bin/zellij",
            "args": ["--layout", "dev"]
        }
    });

    for provider in &config.ai.providers {
        let (name, path) = match provider {
            crate::config::AiProvider::Claude => ("claude", "/usr/local/bin/claude"),
            crate::config::AiProvider::Aider => ("aider", "/usr/local/bin/aider"),
            crate::config::AiProvider::Gemini => ("gemini", "/usr/local/bin/gemini"),
            crate::config::AiProvider::Mistral => ("mistral", "/usr/local/bin/mistral"),
        };
        terminal_profiles.as_object_mut().unwrap().insert(
            name.to_string(),
            serde_json::json!({ "path": path }),
        );
    }

    // Build VS Code settings — start with base, add flavor-specific
    let mut settings = serde_json::json!({
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.fontFamily": "'FiraCode Nerd Font', 'Hack Nerd Font', 'JetBrainsMono Nerd Font', monospace",
        "terminal.integrated.profiles.linux": terminal_profiles
    });

    // LaTeX Workshop settings — matches proven setup from derived projects
    if addons.has_latex() {
        let latex_settings = serde_json::json!({
            "latex-workshop.latex.outDir": "./out",
            "latex-workshop.view.pdf.viewer": "tab",
            "latex-workshop.latex.tools": [
                {
                    "name": "latexmk-lualatex",
                    "command": "latexmk",
                    "args": [
                        "--shell-escape",
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdflatex=lualatex",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "latexmk-pdflatex",
                    "command": "latexmk",
                    "args": [
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "biber",
                    "command": "biber",
                    "args": [
                        "--input-directory=out",
                        "--output-directory=out",
                        "%DOCFILE%"
                    ]
                }
            ],
            "latex-workshop.latex.recipes": [
                {
                    "name": "latexmk (lualatex)",
                    "tools": ["latexmk-lualatex"]
                },
                {
                    "name": "latexmk (pdflatex)",
                    "tools": ["latexmk-pdflatex"]
                },
                {
                    "name": "latexmk (lualatex) + biber",
                    "tools": ["latexmk-lualatex", "biber", "latexmk-lualatex"]
                }
            ],
            "latex-workshop.latex.autoBuild.run": "onSave",
            "latex-workshop.latex.clean.fileTypes": [
                "*.aux", "*.bbl", "*.blg", "*.fdb_latexmk", "*.fls",
                "*.log", "*.out", "*.synctex.gz", "*.toc", "*.lof",
                "*.lot", "*.nav", "*.snm", "*.vrb", "*.bcf", "*.run.xml"
            ]
        });
        for (k, v) in latex_settings.as_object().unwrap() {
            settings
                .as_object_mut()
                .unwrap()
                .insert(k.clone(), v.clone());
        }
    }

    // Use serde_json for proper JSON formatting
    let mut devcontainer = serde_json::json!({
        "name": name,
        "dockerComposeFile": "docker-compose.yml",
        "service": name,
        "workspaceFolder": "/workspace",
        "overrideCommand": true,
        "remoteUser": config.container.user,
        "customizations": {
            "vscode": {
                "extensions": extensions,
                "settings": settings
            }
        }
    });

    // Insert postCreateCommand if configured
    if let Some(cmd) = &config.container.post_create_command {
        devcontainer
            .as_object_mut()
            .unwrap()
            .insert("postCreateCommand".to_string(), serde_json::json!(cmd));
    }

    // Network keepalive — lightweight DNS lookup every 2 min to prevent
    // OrbStack/VM NAT from dropping idle connections.
    if config.container.keepalive {
        devcontainer.as_object_mut().unwrap().insert(
            "postStartCommand".to_string(),
            serde_json::json!(
                "nohup bash -c 'while true; do nslookup example.com > /dev/null 2>&1; sleep 120; done' > /dev/null 2>&1 &"
            ),
        );
    }

    // Prevent VS Code from auto-forwarding the PulseAudio port (fixes #11)
    if config.audio.enabled {
        // Extract port from pulse_server string (e.g., "tcp:host.docker.internal:4714")
        let port = config
            .audio
            .pulse_server
            .rsplit(':')
            .next()
            .unwrap_or("4714");
        devcontainer.as_object_mut().unwrap().insert(
            "portsAttributes".to_string(),
            serde_json::json!({
                port: { "onAutoForward": "ignore" }
            }),
        );
    }

    // Serialize with pretty formatting
    let json_str = serde_json::to_string_pretty(&devcontainer)
        .context("Failed to serialize devcontainer.json")?;

    // Add the header as a comment at the top (JSON doesn't support comments,
    // but devcontainer.json does via jsonc)
    let header = format!(
        "// Generated by aibox v{} — do not edit manually.\n// To modify, edit aibox.toml and run: aibox sync\n",
        config.aibox.version
    );

    write_if_changed(
        &dir.join("devcontainer.json"),
        &format!("{}{}\n", header, json_str),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;

    fn test_env() -> minijinja::Environment<'static> {
        create_template_env()
    }

    fn addons_with(names: &[&str]) -> crate::config::AddonsSection {
        use crate::config::{AddonToolsSection, AddonsSection};
        use std::collections::HashMap;
        let mut addons = HashMap::new();
        for name in names {
            addons.insert(
                name.to_string(),
                AddonToolsSection {
                    tools: HashMap::new(),
                },
            );
        }
        AddonsSection { addons }
    }

    fn make_config(addon_names: &[&str], audio_enabled: bool) -> AiboxConfig {
        let mut config = crate::config::test_config();
        config.aibox.version = "1.2.3".to_string();
        config.container.name = "test-ctr".to_string();
        config.container.hostname = "test-host".to_string();
        config.addons = addons_with(addon_names);
        config.audio = AudioSection {
            enabled: audio_enabled,
            pulse_server: "tcp:localhost:4714".to_string(),
        };
        config
    }

    #[test]
    fn generate_all_creates_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let devcontainer = dir.path().join(".devcontainer");
        // We need to run generate functions directly on the temp dir
        // Since generate_all uses relative paths, we test the individual generators
        fs::create_dir_all(&devcontainer).unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, &devcontainer, &test_env()).unwrap();
        generate_docker_compose(&config, &devcontainer, &test_env()).unwrap();
        generate_devcontainer_json(&config, &devcontainer).unwrap();

        assert!(devcontainer.join("Dockerfile").exists());
        assert!(devcontainer.join("docker-compose.yml").exists());
        assert!(devcontainer.join("devcontainer.json").exists());
    }

    #[test]
    fn dockerfile_contains_correct_from_image() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains(&format!(
                "FROM {}:base-debian-v{} AS aibox",
                crate::config::IMAGE_REGISTRY,
                config.aibox.version
            )),
            "Dockerfile should reference base-debian image with correct tag format and stage alias"
        );
    }

    #[test]
    fn dockerfile_includes_extra_packages() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.extra_packages = vec!["ripgrep".to_string(), "fd-find".to_string()];
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("ripgrep"), "should include ripgrep");
        assert!(content.contains("fd-find"), "should include fd-find");
        assert!(
            content.contains("apt-get install"),
            "should have apt-get install"
        );
    }

    #[test]
    fn dockerfile_no_extra_run_when_no_packages() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("apt-get"),
            "should not have apt-get when no extra packages"
        );
    }

    #[test]
    fn compose_contains_container_name_and_hostname() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("container_name: test-ctr"));
        assert!(content.contains("hostname: test-host"));
    }

    #[test]
    fn compose_includes_audio_when_enabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], true);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("PULSE_SERVER"),
            "should have PULSE_SERVER env"
        );
        assert!(
            content.contains("AUDIODRIVER"),
            "should have AUDIODRIVER env"
        );
        assert!(content.contains(".asoundrc"), "should mount .asoundrc");
    }

    #[test]
    fn compose_excludes_audio_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("PULSE_SERVER"));
        assert!(!content.contains("AUDIODRIVER"));
        assert!(!content.contains(".asoundrc"));
    }

    #[test]
    fn compose_includes_extra_volumes() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.extra_volumes = vec![ExtraVolume {
            source: "/host/data".to_string(),
            target: "/container/data".to_string(),
            read_only: true,
        }];
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("/host/data:/container/data:ro"));
    }

    #[test]
    fn compose_includes_extra_environment() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config
            .container
            .environment
            .insert("FOO".to_string(), "bar".to_string());
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("FOO: \"bar\""));
    }

    #[test]
    fn dockerfile_appends_local_when_present() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "RUN npx playwright install --with-deps chromium\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("# Project-specific layers (from Dockerfile.local"),
            "should have local layers comment"
        );
        assert!(
            content.contains("playwright"),
            "should include Dockerfile.local content"
        );
    }

    #[test]
    fn dockerfile_skips_empty_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        fs::write(dir.path().join("Dockerfile.local"), "  \n").unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment for empty file"
        );
    }

    #[test]
    fn dockerfile_works_without_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment when no Dockerfile.local"
        );
    }

    #[test]
    fn dockerfile_local_with_multistage() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "FROM node:20 AS node-builder\nRUN npm ci\n\nFROM aibox\nCOPY --from=node-builder /app /app\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("FROM node:20 AS node-builder"));
        assert!(content.contains("FROM aibox"));
        assert!(content.contains("COPY --from=node-builder"));
    }

    #[test]
    fn devcontainer_json_python_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
    }

    #[test]
    fn devcontainer_json_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["latex"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("james-yu.latex-workshop"));
        assert!(content.contains("mblode.zotero"));
    }

    #[test]
    fn devcontainer_json_rust_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["rust"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("rust-lang.rust-analyzer"));
    }

    #[test]
    fn devcontainer_json_python_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python", "latex"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn devcontainer_json_typst_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["typst"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_python_typst_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python", "typst"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_includes_post_create_command() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.post_create_command = Some("pip install foo".to_string());
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("postCreateCommand"),
            "should contain postCreateCommand key"
        );
        assert!(
            content.contains("pip install foo"),
            "should contain the command value"
        );
    }

    #[test]
    fn devcontainer_json_includes_keepalive() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.keepalive = true;
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("postStartCommand"),
            "should contain postStartCommand key"
        );
        assert!(
            content.contains("nslookup"),
            "should contain keepalive nslookup command"
        );
    }

    #[test]
    fn devcontainer_json_excludes_keepalive_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            !content.contains("postStartCommand"),
            "should not contain postStartCommand when keepalive is disabled"
        );
    }

    #[test]
    fn devcontainer_json_includes_custom_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.vscode_extensions = vec!["eamodio.gitlens".to_string()];
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("eamodio.gitlens"),
            "should contain custom extension"
        );
    }

    #[test]
    fn devcontainer_json_base_no_extra_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("ms-python.python"));
        assert!(!content.contains("rust-lang.rust-analyzer"));
        assert!(!content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn dockerfile_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.starts_with("# Generated by aibox v1.2.3"));
    }

    #[test]
    fn compose_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.starts_with("# Generated by aibox v1.2.3"));
    }

    #[test]
    fn devcontainer_json_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.starts_with("// Generated by aibox v1.2.3"));
    }

    #[test]
    fn devcontainer_json_claude_terminal_profile() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("claude"), "default config should include claude profile");
    }

    #[test]
    fn devcontainer_json_no_ai_terminal_profiles_when_empty() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![];
        config.resolve_ai_provider_addons();
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("claude"), "should not have claude profile");
        assert!(!content.contains("aider"), "should not have aider profile");
        assert!(content.contains("bash"), "should still have bash profile");
    }

    #[test]
    fn devcontainer_json_aider_terminal_profile() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("aider"), "should have aider profile");
        assert!(!content.contains("claude"), "should not have claude profile");
    }

    #[test]
    fn dockerfile_includes_aider_install() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("aider"), "should install aider");
        assert!(content.contains("uv tool install"), "should use uv tool install");
    }

    #[test]
    fn dockerfile_claude_installed_via_addon() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![crate::config::AiProvider::Claude];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        // Claude is now installed via addon pipeline, not baked into base image
        assert!(content.contains("claude.ai/install.sh"), "should install Claude via addon");
        assert!(!content.contains("aider"), "should not install aider");
        assert!(!content.contains("gemini"), "should not install gemini");
    }

    #[test]
    fn compose_includes_aider_volume() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains(".aider"), "should have aider volume mount");
    }

    #[test]
    fn compose_includes_gemini_volume() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![crate::config::AiProvider::Gemini];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains(".gemini"), "should have gemini volume mount");
    }

    #[test]
    fn compose_no_ai_volumes_when_empty() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.providers = vec![];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains(".claude"), "should not have claude volume");
        assert!(!content.contains(".aider"), "should not have aider volume");
        assert!(!content.contains(".gemini"), "should not have gemini volume");
    }
}
